### ISSUE TITLE
Add support for `62red` endless labels

### ISSUE THREAD

**Issue by EnsuingRequiem** [sam159/brotherql_grocylabels#3]
QL-820NWBc printers come with the 62mm endless tape which supports red. Without properly calling `create_label` within `sendToPrinter` in `__init__.py`, the printer will error due to an incorrect tape size. Remedy the issue by including the `red` parameter in the call.  Review https://github.com/pklaus/brother_ql_web/blob/9e20b6dc/brother_ql_web.py#L201 for how the author of `brother_ql` implemented the red labels in their version of `brother_ql_web`

**Comment by sam159** [comment]
Looks straight-forward enough, will update the issue when i've got something to test

**Comment by sam159** [comment]
@EnsuingRequiem can you give the image `sam159/brotherql_grocylabels:feature-red-label-support` a go as see if works correctly for red labels?

**Comment by EnsuingRequiem** [comment]
I should be able to update my Compose file tomorrow and test it out

**Comment by EnsuingRequiem** [comment]
> @EnsuingRequiem can you give the image `sam159/brotherql_grocylabels:feature-red-label-support` a go as see if works correctly for red labels?

I checked it and it prints without requiring me to make any adjustments. Thanks!

**Comment by sam159** [comment]
Thanks for testing! thats all merged in now and you can switch to the `latest` tag :)
